### PR TITLE
Orbwalker: Randomizing delay between ticks.

### PR DESCRIPTION
**Pull request by DZ191**

### CODE REVIEW

**Comment by Hellsing** [comment]
Adding that in the Game.OnUpdate loop is contra productive, as it would generate a new random several times a second which increases the chance that your 0-15 ms random turns into something like 0-2 ms random, I would suggest storing a generated random value each time you set the last movement command time, but hey, it's just a suggestion ;)

**Comment by SephLeague** [comment]
I agree it shouldn't do it so often but its not going to have an effect on the probability. Its like rolling a dice more often and saying it will land on 1 and 2 more often which is not true.

**Comment by Hellsing** [comment]
Because the chances are higher that it will generate a lower random number which will make it pass the if condition earlier than you might wanted. And since Game.OnUpdate spams like hell the chances are very high that it will generare all numbers very often, and that includes 0-2 aswell.

**Comment by legacy3** [comment]
alt tag

**Comment by myo** [comment]
so true

**Comment by SephLeague** [comment]
"Because the chances are higher that it will generate a lower random number". What are you even saying? Everything is just as likely, its just happening more often.

**Comment by myo** [comment]
tumblr_nqz7263rjl1szmtqio1_500

**Comment by gamepost** [comment]
Meow. ^.^

**Comment by DZ191** [comment]
Kitty! *pats*

**Comment by ChewyMoon** [comment]
facepalm

**Pull request merged**
