### PR TITLE
Improve Spell.cs and Utility.cs for more useful

### PR DESCRIPTION
**Pull request by brian0305**

### CODE REVIEW

**Comment by trees-software** [comment]
Yeah, you need to remove the IsMe check. Most self cast spells are casted on yourself.

**Comment by brian0305** [comment]
Edited. Check again Tree

**Comment by trees-software** [comment]
Why did you change the range checks to valid target checks? Why does it matter if the units are targetable or not? That should be handled by the assembly using the function.

**Comment by brian0305** [comment]
It should be ok. Right?

**Pull request merged**
