### PR TITLE
Update Orbwalking.cs

### PR DESCRIPTION
**Pull request by nabbhacker**
Added Missing documentation + Nautilus's W AA Reset.

### CODE REVIEW

**Comment by SephLeague** [comment]
but nautilus is already there :roto2:

**Comment by xcsoftforlsharp** [comment]
http://i.imgur.com/fZ0kwin.png

:disappointed:

**Comment by nabbhacker** [comment]
OH FOR FUCK SAKE

sorry i'm fucking blind fucking sunday night FUCK

**Comment by legacy3** [comment]
i trust you one time...

**Comment by nabbhacker** [comment]
Sorry, i pull requested you again.

**Pull request merged**
