### PR TITLE
Fake Clicks

### PR DESCRIPTION
**Pull request by pean153**
Adds Move To Mouse and FakeClicks (https://www.joduska.me/forum/topic/37695-5x-fakeclicks-handy-for-streamers) to Common orbwalker.
The FakeClicks are smooth in common compared to standalone assembly because in common it is loaded into orbwalker which isn't possible in standalone assembly.

Also, sorry I don't know how to separate these 2 additions to make 2 pulls because I can't fork l#.common twice (I don't know how lol)

### CODE REVIEW

**Comment by trees-software** [comment]
Can you redo this as a single commit and not modify csproj file?

**Comment by pean153** [comment]
RIP How do I fork twice? :D I will try give me sec

**Comment by pean153** [comment]
Uh I actually need System.Windows.Forms to use Control in VirtualMouse. How do I not modify csproj?

**Comment by trees-software** [comment]
You can modify it, but only to add references. Don't change the path of the other references.

**Comment by pean153** [comment]
Is it good like it is now? I don't see any modifications into the csproj other than the reference.
For some reasons it shows + and - even tho there is no visual change for me in the #region and at the last bracket of the file. Is that bug or?

**Pull request merged**
