### PR TITLE
Removed Deathfire Grasp

### PR DESCRIPTION
**Pull request by jQueryBase64MyAss**
Deathfire Grasp removed 5.2

### CODE REVIEW

**Comment by Crisdmc** [comment]
Noooooooooooooooooo.

**Comment by ChewyMoon** [comment]
Good to wait a bit for people to remove this, I'll add an obsolete message.

**Comment by jQueryLeagueSharp** [comment]
Noticed that it would break other stuff if you removed it like this straight away

**Comment by WorstPing** [comment]
Added an obsolete message, will be removed at 5.4

**Pull request closed without merging**
