### PR TITLE
Fix AoEPrediction

### PR DESCRIPTION
**Pull request by mystexodus**
Fix spelling and fix a bug that allowed the filtered unit to be added to
the list of possible targets multiple times.

### CODE REVIEW

**Comment by xmirai** [comment]
Oic! merge merge!

**Comment by xmirai** [comment]
Did you end up fixing the Z value multiplication issue also?

**Comment by mystexodus** [comment]
No I don't think that branch of code really comes into play so haven't fixed it yet just raised an issue. Don't have time to text a fix right now.

**Comment by TheSaltyWaffle** [comment]
:+1:

**Comment by Beaving** [comment]
This needs to be obsoleted so existing code doesn't break. Feel free to make a new pull request.

**Comment by mystexodus** [comment]
What do you mean not needed? It's the fix. The loop of enemies modifies input.Unit to do the predictions which causes the original where clause to no longer filter the source unit correctly by network id.

**Comment by mystexodus** [comment]
If it's clearer the alternative is to make the link query a list so it's contents don't change while iterating it...

**Comment by Beaving** [comment]
The .Where() is executed and the list is saved in memory. THEN the for loop is executed, thats why it is not needed.

**Comment by TheSaltyWaffle** [comment]
Make a new pull request and don't change the spelling error of "possible"

**Comment by mystexodus** [comment]
Beaving, that is not how it works, it's an enumerator not a list so the contents change while iterating. That assumption is the exact defect that has aoe prediction broken.

**Comment by Beaving** [comment]
We've briefly discussed it in our skype group and we weren't so sure about it. After some more dedication to this issue I've figured you are right. Finally Karthus Q AoE prediction should be OP now :P

**Pull request merged**
