### PR TITLE
ItemData update, Geometry/Utility/Orbwalking improvements.

### PR DESCRIPTION
**Pull request by WorstPing**

### CODE REVIEW

**Comment by Hellsing** [comment]
Why can't you just leave the Orbwalking as it is? I don't understand that...

**Comment by WorstPing** [comment]
The loop var is not updated per loop, that's why you need to add an array for it which fixes it.

**Comment by Hellsing** [comment]
Oh I didn't fully read it, though you made another change like Trees did :D

**Comment by WorstPing** [comment]
^^ Nope, just fixing up some issues. Not going to touch yours and Trees area of "combat" :D

**Pull request merged**
