### PR TITLE
Added "Still Combo" an orbwalk mode that disables movement.

### PR DESCRIPTION
**Pull request by myo**
It's STILL the Combo orbwalking mode, but you stand still during it. Genius, right?

### CODE REVIEW

**Comment by DZ191** [comment]
I rate 8/8

**Comment by jQueryBase64MyAss** [comment]
fu u @DZ191

**Comment by DZ191** [comment]
@jQueryBase64MyAss no u

**Comment by SephLeague** [comment]
Can you make it all 1 Commit? Thanks

**Comment by myo** [comment]
alright

**Pull request closed without merging**
