### PR TITLE
Farm delay default value lowered from 30 to 0

### PR DESCRIPTION
**Pull request by zezzy**

### CODE REVIEW

**Comment by nabbhacker** [comment]
#friendzonedzezzy :feelsbadman:

**Comment by zezzy** [comment]
I haven't decided to merge yet, the difference is too close to tell: https://www.joduska.me/forum/topic/178935-poll-last-hitting-farm-delay/

**Comment by nabbhacker** [comment]
mh..

**Comment by jQueryBase64MyAss** [comment]
stop spam the dev chat jesus

**Comment by jQueryBase64MyAss** [comment]
people trying to work

**Pull request merged**
