### PR TITLE
RekSai Damage

### PR DESCRIPTION
**Pull request by SKOx0**

### CODE REVIEW

**Comment by Hellsing** [comment]
E calculation is wrong as it is true damage and also it does not double the damage. You can also put the overall E damage in one stage rather than adding a second just for max fury.

**Comment by Hellsing** [comment]
Didn't mean to close, sorry :D

**Comment by SKOx0** [comment]
np, thx my favorite hater :p /j

**Comment by Hellsing** [comment]
I'm no hater lol :D Just merge the E into one stage and I'll merge your PR

**Comment by SKOx0** [comment]
I'm just kidding Kappa, u downvoted my topics =( made me sad

**Comment by Hellsing** [comment]
No, change the damage type from Physical to True as soon as he has max fury. This way you don't need the extra stage you added. Told you to do that already :P

**Pull request closed without merging**
