### PR TITLE
Added Titanic Hydra to ItemData.cs

### PR DESCRIPTION
**Pull request by nabbhacker**

### CODE REVIEW

**Comment by xcsoftforlsharp** [comment]
:disappointed:

**Comment by nabbhacker** [comment]
yup.

**Comment by nabbhacker** [comment]
yup.

**Comment by brian0305** [comment]
3053 is wrong

**Comment by SephLeague** [comment]
Yeah its 3748 :santa:

**Comment by legacy3** [comment]
:cry:

**Comment by ChewyMoon** [comment]
:wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink: :wink:

**Pull request merged**
