### PR TITLE
Does not belong here at all.

### PR DESCRIPTION
**Pull request by jQueryBase64MyAss**

### CODE REVIEW

**Comment by myo** [comment]
PJSalt it works

**Comment by jQueryBase64MyAss** [comment]
No it does NOT work

**Comment by jQueryBase64MyAss** [comment]
The ward placed cannot be targeted by allies, so it cannot be used as a Teleport.png Teleport target or for the purposes of 'ward jumping' such as with Lee Sin Lee Sin's Safeguard.png Safeguard.
The ward only has 1 hitpoint.

**Comment by ChewyMoon** [comment]
good shit

**Comment by xcsoftforlsharp** [comment]
:100:

**Pull request merged**
