### PR TITLE
updated IsWard checking by health more lightweight (2)

### PR DESCRIPTION
**Pull request by mirinsharp**
Updated it again, ty hellsing

### CODE REVIEW

**Comment by LSFree** [comment]
Hmm, I think Zyra plants and such would pass the unit.MaxHealth checks. Just  unit.CharData.BaseSkinName.ToLower().Contains("ward") or unit.CharData.BaseSkinName.Contains("Ward") would probably cut the overhead a bit, though.

**Comment by brian0305** [comment]
this code so horrible :o check maxhealth multi times? Why sould do that?

**Comment by ShineSharp** [comment]
@brian0305 Its more "clear" to understand they are ward hps, also in runtime with "||" operator, it wont check other conditions after first "true" result

**Comment by brian0305** [comment]
why just dont check name ? it just more faster you doing this bcz minion still can have 1hp left b4 die

**Comment by Hellsing** [comment]
Well, it's checking for MaxHealth and not for the current health my friend :P

**Comment by brian0305** [comment]
^ Hellsing, sorry :D i just dont take a look closer. But i still prefer check name, it will work for pet of champion too. Here is full list name of pet !!!
var pets = new[]
                           {
                               "annietibbers", "elisespiderling", "heimertyellow", "heimertblue", "leblanc",
                               "malzaharvoidling", "shacobox", "shaco", "yorickspectralghoul", "yorickdecayedghoul",
                               "yorickravenousghoul", "zyrathornplant", "zyragraspingplant"
                           };

**Comment by ShineSharp** [comment]
@brian0305 you are saying why you check health multp. times, but you 
dont know comparing strings is more expensive ? string compare checks two strings char by char so  that means there is a lot of compares.

**Comment by brian0305** [comment]
but do you have max health of shaco box? or maxhealth of Zyra plant ? or heimer turret??? He said trying to make Common Orbwalk attack thoes object so the best way to do is checkname. just use pets.contains than problem solve, attack what ever object you want

**Comment by ShineSharp** [comment]
It was just for wards lol

**Pull request closed without merging**
