### PR TITLE
Trying to count minion Aggro

### PR DESCRIPTION
**Pull request by robdylan**
Please have a look. I didn't receive any errors but I'm not sure if it works as intended.

### CODE REVIEW

**Comment by Everesty** [comment]
Well, for one, you shouldn't need a `using LeagueSharp.Common` when you're working in the Common namespace (which you are).

Secondly, what's up with having a public readonly dictionary, and then also having a public property to get that public dictionary?

Also, for the part where you changed the orbwalker: you `OrderBy` 3 times, and since the last `OrderBy` is the same that was alone prior to your changes, the whole list is _still_ going to be in the same order as it was before the changes you made, though there is a chance that minions with the same health value will be in a different order than they were before. Nonetheless, your change to the orbwalker itself is practically useless, currently.

Another thing, due to lack of use of ReSharper and/or StyleCop, your code doesn't really follow the [coding standards](https://www.joduska.me/forum/topic/18575-leaguesharp-coding-standards/) and looks a bit weird in relation to all other code. I, for one, wasn't too happy about the tabbing in the linq-chaining for the orbwalker change.

Finally, why is this even needed? What's the purpose of counting how many auto attacks there are in a dictionary (why a dictionary and not a list???) that is never even added to? I can't see a reasoning behind this, so I think it'd be useful to explain why this change is needed c: .

**Comment by DZ191** [comment]
Hello friend,

unfortunately you PR has some very severe flaws, some of which have already been mentioned.

First of all, although you added the MinionAggro class it is completely useless, as you never add anything to the dictionary itself. A better way would have been to add a getter to the Dictionary inside HealthPrediction and work with that.

Also I am pretty sure the use of OrderBy you did is incorrect. For starters:
https://github.com/LeagueSharp/LeagueSharp.Common/pull/294/files#diff-b1c17c0c17c65107116502d2db4de7e2R715

This makes no sense because you're counting the entries of the dictionary as a whole (which doesn't have anything added to it as of now anyways, but that's another story). It's incorrect because you should be using the count of attacks that are directed towards a certain minion.

Lastly the last OrderByDescending nullifies all the previous OrderBy s, as *Everest* mentioned.

On a side note, the correct usage of consecutive OrderBys in LinQ is done with 'OrderBy(<T>).ThenBy(<T>)' and is usually only effective if done on different fields of the same object. 

Cheers,
*Asuna*

**Comment by iJavai** [comment]
Hello, I'm a ninja...

**Comment by step1step2** [comment]
Alright, thank you very much for your feedback. I appreciate it very much.
I followed iMeh's Guide on how to install RedSharper and StyleCop. I didn't find Resharper-StyleCop Plugin tho. I'm going to assume I couldn't find it because it was installed already.

ReSharper's 'Cleanup Code' literally reformatted the entire project. Do you agree with the formatting or should I keep files like they are?

**Comment by Everesty** [comment]
It's probably best to keep files as they were before you used cleanup code. I only mentioned ReSharper to fix more minor things like your public field being camelCase (as opposed to PascelCase) and to have your linq-chaining look more like:

```c#
var MinionList =
    ObjectManager.Get<Obj_AI_Minion>()
        .Where(
            minion =>
                +minion.IsValidTarget() && InAutoAttackRange(minion) &&
                minion.Health <
                2 * (ObjectManager.Player.BaseAttackDamage + ObjectManager.Player.FlatPhysicalDamageMod))
        .OrderBy(cannonMinion => cannonMinion.CharData.BaseSkinName.Contains("Siege"))
        .OrderBy(minionAggro => MinionAggro.ActiveAttacks.Count())
        .OrderByDescending(minionHealth => minionHealth.Health);
```

I wasn't expecting a full-code cleanup. :P

**Comment by step1step2** [comment]
Alright, good point :-P

**Comment by step1step2** [comment]
Fixed the formatting. It should work now. However Lizzaran has already created a new pull request.

I modified quite a few things with the help of RedSharper. I recommend you to merge both pull requests.

**Comment by step1step2** [comment]
Nvm then, go with Lizzaran pull request.

**Comment by SephLeague** [comment]
Lizzarans was merged.

**Pull request closed without merging**
