### PR TITLE
Update Orbwalking.cs

### PR DESCRIPTION
**Pull request by nabbhacker**
Fixed Fiora's E Reset.
Added Nidalee R.

### CODE REVIEW

**Comment by legacy3** [comment]
l# data plx

**Comment by nabbhacker** [comment]
Already fixed in l#.data

**Comment by nabbhacker** [comment]
Dw :yum:

**Comment by legacy3** [comment]
then use l# data?

**Comment by nabbhacker** [comment]
i do?

**Comment by legacy3** [comment]
call me a noob but thats a stringlist https://s.put.re/FgfFDp1.png

**Comment by ChewyMoon** [comment]
thats actually a string array

**Comment by legacy3** [comment]
Sorry, in my Bash-At-Random-Devs mood, I had a fogged view!

**Comment by ChewyMoon** [comment]
Understandable!

**Comment by nabbhacker** [comment]
useless bash, since i did nothing but fixing a common bug
:fappa:

**Pull request merged**
