### PR TITLE
Update Orbwalking.cs

### PR DESCRIPTION
**Pull request by nabbhacker**
Added Jhin's Q to AutoAttack-Resets.

### CODE REVIEW

**Comment by xcsoftforlsharp** [comment]
:frowning:

**Comment by xKurisu** [comment]
It doesn't reset xD

**Comment by jQueryBase64MyAss** [comment]
but the card said...

**Comment by legacy3** [comment]
nigga please, stop breaking stuff

**Comment by nabbhacker** [comment]
http://puu.sh/n4Cj1/35dd2d0c62.png

You what m8s

**Comment by jQueryBase64MyAss** [comment]
xxx

for example cancel != reset

**Comment by nabbhacker** [comment]
Alright then, mb

**Comment by xKurisu** [comment]
no problem m8

**Comment by zezzy** [comment]
Please test before you propose a change for something. Thank you.

**Comment by nabbhacker** [comment]
? I just read it and i thought you guys missed it, i also said mb, what's the problem?

**Comment by zezzy** [comment]
Just so you are aware for the future, sorry for the confusion!

**Comment by legacy3** [comment]
zezzy pls, you dont even contribute

**Comment by xcsoftforlsharp** [comment]
:disappointed:

**Comment by jQueryBase64MyAss** [comment]
Gay for Snow

**Comment by nabbhacker** [comment]
jcurry pls

**Comment by badao** [comment]
close please

**Pull request closed without merging**
