### PR TITLE
Correction recovery Button can not be used

### PR DESCRIPTION
**Pull request by as112200**

### CODE REVIEW

**Comment by legacy3** [comment]
arent you just reverting sephs commit

**Comment by as112200** [comment]
We are using XCV to use no response

**Comment by SephLeague** [comment]
Hi

Not sure what you mean exactly by recovery button but since you said XCV I assume we are talking about the Orbwalker keys. It works fine here. It could be caused by something else, please take a picture of your console while it is happening and send it to me on the forums or here.

Thank you

**Comment by as112200** [comment]
We have some users in Taiwan. When in use . Key invalid
But some users are normal 
Don't know where the problem is.
This change
Things happen only after

**Pull request closed without merging**
