### PR TITLE
Add of the real name of Sivir's Spell Shield (E) and rename of a variable

### PR DESCRIPTION
**Pull request by max0120LSharp**
I checked a ToDo with add the real of the Sivir's Spell Shield (E) and rename a variable, target is more clear than a simple t. To improve the reading of the code. 

I'll try to fix now the missnamed variable to be good with coding standard.

### CODE REVIEW

**Comment by h3h3** [comment]
https://github.com/max0120LSharp/LeagueSharp.Common/blob/master/TargetSelector.cs#L280
https://github.com/max0120LSharp/LeagueSharp.Common/blob/master/TargetSelector.cs#L293
Still missing :(

**Comment by max0120LSharp** [comment]
I've add only for Sivir. I didn't find for the real name of the banshee veil but I'll add for nocturne. I just need to commit my corrections on all name of variable to be correct with our code's standard.

**Comment by max0120LSharp** [comment]
I tried to verify for nocturne & banshee's veil but i'm not sure so I prefer stay like that

**Comment by max0120LSharp** [comment]
I think the name that are already in place are good in my opinion :)

**Pull request closed without merging**
