### PR TITLE
Add SData to AfterAttack callback

### PR DESCRIPTION
**Pull request by aikoy**
I was working on a Quinn script only to realize that I can't find out if my AA is an "enhanced" AA through the callback. This addition would help us out a lot.

### CODE REVIEW

**Comment by ChewyMoon** [comment]
Just subscribe to the before attack and see if the target has the e buff..?

**Comment by aikoy** [comment]
Why work around something when a solution is so simple? (Also I could see other uses for an SData parameter)

**Comment by Hellsing** [comment]
Cuz this "solution" will break all scripts that are using the after attack event...

**Comment by aikoy** [comment]
ok hellsing

**Comment by h3h3** [comment]
There is a reason to use EventArgs for Events, you could just add it to the EventArgs class without breaking any Assemblies.

**Pull request closed without merging**
