### PR TITLE
General Improvement

### PR DESCRIPTION
**Pull request by Loggan08**
Accidentally removed all usings to SharpDX, otherwise maybe 2-3 mistakes at most.

Everything should be better.

### CODE REVIEW

**Comment by Loggan08** [comment]
Nvm this, will redo the whole thing properly, this was just a test

**Comment by Loggan08** [comment]
Ok, reverted the original commit and did everything properly, this should be safe to accept.

Finished everything off with a reformat of the code.

**Comment by Hellsing** [comment]
This is just pure Resharper lol. We have a Resharper profile on the forums, if you use that you should not have any differences I guess...

**Comment by Loggan08** [comment]
Nothing to do with which profile is used, it is about code improvement.

**Comment by Hellsing** [comment]
When talking about improvements you should really improve your commit messages and also the amount of commits for one PR.

**Comment by Loggan08** [comment]
Well you can always check the changes in the file and then commit them yourself, no need to accept this, i am just proposing changes

**Comment by Hellsing** [comment]
Ye, but for example this: This would fuck up so many scripts by changing those methods to private. You don't even know if people use this or not, your PR would basically fuck everything up!

https://github.com/Loggan08/LeagueSharp.Common/commit/d4f3af57ae4ddb28a9580d24280ef6d938f4cbc5

**Comment by Loggan08** [comment]
Changed them to private because they are only used in that class, and if they are only used in that class they can be made private

**Comment by Loggan08** [comment]
I might be mistaken how leaguesharp works, but if I'm wrong there are still many valid changes in there (all those publics can be changed back to private), but the remaining changes are at least valid.

**Pull request closed without merging**
