### PR TITLE
Kappa

### PR DESCRIPTION
**Pull request by Crisdmc**
Is right?

### CODE REVIEW

**Comment by Crisdmc** [comment]
kappa?

**Comment by ChewyMoon** [comment]
The parameter isn't used(yet) just leave it to the default value.

**Comment by Crisdmc** [comment]
This parameter was used for case insensitive, but now its default.

StringComparison.CurrentCultureIgnoreCase

**Comment by Crisdmc** [comment]
But really it does not change anything, not improve anything.

You can close :+1: . Thank you.

**Pull request closed without merging**
