### PR TITLE
ChoGath R

### PR DESCRIPTION
**Pull request by Crisdmc**
Add dmg calc for ChoGath R, attacking minion.

This time I tested :)

Sorry about kappa pull.

I made the change, and installed from my repository in l #, tested the calculations and is working, both for player and minion.

Added the ult in my activator, so I can use the calculation of the common, and will not involve problem for others, only improvement.

Thank you.

### CODE REVIEW

**Comment by Crisdmc** [comment]
Give love to my PR ^^

**Comment by Crisdmc** [comment]
wontfix ? I already did the test and it works, before commit. Maybe you have not checked right, or it what will not fix?

**Comment by ChewyMoon** [comment]
I tagged wontfix since this is an old issue that has been ignored/unseen.

**Comment by Crisdmc** [comment]
@ChewyMoon ahh, my sorry my mistake, I thought it meant something else.

**Pull request merged**
