### PR TITLE
Added Poppy ult.

### PR DESCRIPTION
**Pull request by step1step2**
I have no idea if this is going to work. I didn't test it. The PR is mainly to notify you that 
derp
doesn't take into account poppy's ultimate.

### CODE REVIEW

**Comment by nabbhacker** [comment]
unit.IsInvulnerable does, simply add that check.

**Comment by step1step2** [comment]
Just checked. There is not entry for Poppy.

**Comment by nabbhacker** [comment]
IsInvulnerable checks for Tryndamere/Kayle/Poppy's ult too.

**Comment by nabbhacker** [comment]
https://github.com/nabbhacker/LeagueSharp.Common/blob/master/TargetSelector.cs

**Comment by step1step2** [comment]
I wasn't able to check it. I don't own poppy and my account is banned.

**Pull request closed without merging**
