### PR TITLE
Orbwalking - Fixed Illaoi attack reset spell name and …

### PR DESCRIPTION
**Pull request by Wiciaki**
…removed the innerly unused Movement Delay

Removed unused using directives across the project
Attempted to make the coding style more consistent

### CODE REVIEW

**Comment by myo** [comment]
:mag: description should be "used R#"

**Comment by Wiciaki** [comment]
I do have it installed but not really, relied on myself more this time :^)

**Comment by nabbhacker** [comment]
While people use R# i use Notepad++ and brain for everything.

I'm a true developer and programmer masterrace.


KappaRoss

**Comment by Wiciaki** [comment]
Thanks for those insightful comments, will use nothing but cmd and notepad from now on

**Comment by nabbhacker** [comment]
Hey i was joking man!

Thanks for the PR.

**Comment by Wiciaki** [comment]
This doesn't need to be merged anymore.

**Comment by myo** [comment]
Hey bro I'm sorry if I sounded rude but that's essentially all I saw in this PR. Thanks for pointing out the orbwalker bug that was really helpful!

**Pull request closed without merging**
