### PR TITLE
Added indexer to the menu class

### PR DESCRIPTION
**Pull request by ChewyMoon**
Also cleaned up code as well as added C# 6 features.

### CODE REVIEW

**Comment by CjShu** [comment]
TargetSelector 208 = Menu.Remove(_configMenu); Err
Orbwalking 932 = Menu.Remove(_config); Err

**Comment by legacy3** [comment]
better remove all of h3h3s code

**Comment by nabbhacker** [comment]
No pls h3h3 is bae

**Comment by h3h3** [comment]
Why would i press Ctrl+F7 before submitting a pull request.

**Pull request closed without merging**
